import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import { motion, useMotionValue, useSpring, useTransform, AnimatePresence } from 'framer-motion';
import './GearCalculator.css';

const GearCalculator = React.memo(() => {
  // State for inputs
  const [t1, setT1] = useState(20);
  const [t2, setT2] = useState(60);
  const [n1, setN1] = useState(1000);
  
  // State for results
  const [results, setResults] = useState({
    gr: 3,
    n2: 333.33,
    tm: 3
  });

  // Animation states
  const [isCalculating, setIsCalculating] = useState(false);
  const [showResults, setShowResults] = useState(true);
  const [hoveredInput, setHoveredInput] = useState(null);
  const [particles, setParticles] = useState([]);

  // --- NEW REPORT GENERATOR FUNCTION ---
  const generateReport = () => {
    const text = `
ENGINEERING ANALYSIS LOG
------------------------
System: Gear Train V2.0
Date: ${new Date().toLocaleString()}

INPUT PARAMETERS:
- Driver Gear (T1): ${t1} Teeth
- Driven Gear (T2): ${t2} Teeth
- Input Speed (N1): ${n1} RPM

CALCULATED OUTPUTS:
- Gear Ratio (GR): ${results.gr}:1
- Output Speed (N2): ${results.n2} RPM
- Torque Multiplier: ${results.tm}x

Status: OPTIMAL
Generated by S. Yoga Vignesh Portfolio
    `;
    const element = document.createElement("a");
    const file = new Blob([text], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `Gear_Analysis_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
  };

  // Refs for animation control
  const driverRef = useRef(null);
  const drivenRef = useRef(null);
  const containerRef = useRef(null);

  // Motion values for smooth animations (optimized spring config)
  const driverRotation = useMotionValue(0);
  const drivenRotation = useMotionValue(0);
  const driverSpring = useSpring(driverRotation, { stiffness: 100, damping: 30, restDelta: 0.001, restSpeed: 0.01, mass: 0.5 });
  const drivenSpring = useSpring(drivenRotation, { stiffness: 100, damping: 30, restDelta: 0.001, restSpeed: 0.01, mass: 0.5 });

  // Create particle effect on calculation (optimized count)
  const createParticles = useCallback(() => {
    const newParticles = [];
    for (let i = 0; i < 8; i++) { // Reduced from 12 to 8
      newParticles.push({
        id: Math.random(),
        x: Math.random() * 100 - 50,
        y: Math.random() * 100 - 50,
        delay: Math.random() * 0.2 // Reduced from 0.3
      });
    }
    setParticles(newParticles);
    setTimeout(() => setParticles([]), 1200); // Reduced from 1500
  }, []);

  // The Calculation Logic with animation (optimized)
  const calculate = useCallback(() => {
    if (!t1 || !t2 || !n1) return;

    setIsCalculating(true);
    setShowResults(false);
    createParticles();

    setTimeout(() => {
      const gr = t2 / t1;
      const n2 = n1 / gr;
      const tm = gr;

      setResults({
        gr: gr.toFixed(2),
        n2: n2.toFixed(2),
        tm: tm.toFixed(2)
      });

      setShowResults(true);
      setIsCalculating(false);
    }, 300); // Reduced from 400ms
  }, [t1, t2, n1, createParticles]);

  // Run calculation with debounce to prevent lag during rapid input changes
  useEffect(() => {
    const debounceTimer = setTimeout(() => {
      calculate();
    }, 150); // Debounce by 150ms
    
    return () => clearTimeout(debounceTimer);
  }, [t1, t2, n1, calculate]);

  // Continuous gear rotation animation with visibility detection for scroll performance
  useEffect(() => {
    if (!containerRef.current) return;
    
    let animationFrame;
    let lastTime = performance.now();
    let isVisible = false;
    const gridBg = containerRef.current.querySelector('.grid-background');
    
    // IntersectionObserver to pause animation when off-screen
    const observer = new IntersectionObserver(
      (entries) => {
        isVisible = entries[0].isIntersecting;
        
        // Pause/resume grid background animation
        if (gridBg) {
          if (isVisible) {
            gridBg.classList.remove('paused');
          } else {
            gridBg.classList.add('paused');
          }
        }
        
        if (isVisible && !animationFrame) {
          lastTime = performance.now();
          animationFrame = requestAnimationFrame(animate);
        }
      },
      { rootMargin: '100px', threshold: 0.01 } // Start animating slightly before visible
    );
    
    const animate = (currentTime) => {
      if (!isVisible) {
        animationFrame = null;
        return;
      }
      
      const deltaTime = (currentTime - lastTime) / 1000; // Convert to seconds
      lastTime = currentTime;
      
      // Driver rotates based on RPM (optimized calculation)
      const driverSpeed = (n1 / 60) * 360 * deltaTime; // degrees per frame based on actual time
      driverRotation.set(driverRotation.get() + driverSpeed * 0.3);
      
      // Driven rotates inversely based on gear ratio
      const ratio = t2 / t1;
      drivenRotation.set(drivenRotation.get() - (driverSpeed / ratio) * 0.3);
      
      animationFrame = requestAnimationFrame(animate);
    };
    
    observer.observe(containerRef.current);
    
    return () => {
      observer.disconnect();
      if (animationFrame) cancelAnimationFrame(animationFrame);
    };
  }, [n1, t1, t2, driverRotation, drivenRotation]);

  return (
    <motion.div 
      className="gear-calculator-wrapper"
      ref={containerRef}
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
    >
      {/* Background grid animation */}
      <div className="grid-background" />
      
      {/* Particle effects */}
      <AnimatePresence>
        {particles.map(particle => (
          <motion.div
            key={particle.id}
            className="particle"
            initial={{ 
              x: 0, 
              y: 0, 
              opacity: 1, 
              scale: 0 
            }}
            animate={{ 
              x: particle.x, 
              y: particle.y, 
              opacity: 0, 
              scale: 1.5 
            }}
            exit={{ opacity: 0 }}
            transition={{ 
              duration: 1.5, 
              delay: particle.delay,
              ease: "easeOut"
            }}
          />
        ))}
      </AnimatePresence>

      <div className="gear-container">
        {/* LEFT PANEL - Inputs */}
        <motion.div 
          className="gear-card inputs-card"
          whileHover={{ y: -5 }}
          transition={{ duration: 0.3 }}
        >
          {/* Corner accents */}
          <div className="corner-accent top-left" />
          <div className="corner-accent top-right" />
          <div className="corner-accent bottom-left" />
          <div className="corner-accent bottom-right" />

          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
          >
            <h1 className="gear-h1">
              <span className="gear-icon">⚙️</span> Gear Train Calculator
            </h1>
            <p className="subtitle">
              <span className="status-dot" />
              System V.2.0 // Real-time Kinematic Analysis
            </p>
          </motion.div>

          {/* Input 1 - Driver Teeth */}
          <motion.div 
            className={`input-group ${hoveredInput === 't1' ? 'hovered' : ''}`}
            onMouseEnter={() => setHoveredInput('t1')}
            onMouseLeave={() => setHoveredInput(null)}
          >
            <label>
              <span className="label-icon">⚡</span>
              Driver Gear Teeth 
              <span className="variable">(T₁)</span>
            </label>
            <div className="input-wrapper">
              <input 
                type="number" 
                value={t1} 
                onChange={(e) => setT1(Number(e.target.value))}
                min="5"
                max="200"
              />
              <motion.div 
                className="input-glow"
                initial={{ opacity: 0 }}
                animate={{ opacity: hoveredInput === 't1' ? 1 : 0 }}
              />
            </div>
            <div className="input-slider">
              <input 
                type="range" 
                min="5" 
                max="200" 
                value={t1}
                onChange={(e) => setT1(Number(e.target.value))}
              />
            </div>
          </motion.div>

          {/* Input 2 - Driven Teeth */}
          <motion.div 
            className={`input-group ${hoveredInput === 't2' ? 'hovered' : ''}`}
            onMouseEnter={() => setHoveredInput('t2')}
            onMouseLeave={() => setHoveredInput(null)}
          >
            <label>
              <span className="label-icon">🔧</span>
              Driven Gear Teeth 
              <span className="variable">(T₂)</span>
            </label>
            <div className="input-wrapper">
              <input 
                type="number" 
                value={t2} 
                onChange={(e) => setT2(Number(e.target.value))}
                min="5"
                max="200"
              />
              <motion.div 
                className="input-glow"
                initial={{ opacity: 0 }}
                animate={{ opacity: hoveredInput === 't2' ? 1 : 0 }}
              />
            </div>
            <div className="input-slider">
              <input 
                type="range" 
                min="5" 
                max="200" 
                value={t2}
                onChange={(e) => setT2(Number(e.target.value))}
              />
            </div>
          </motion.div>

          {/* Input 3 - RPM */}
          <motion.div 
            className={`input-group ${hoveredInput === 'n1' ? 'hovered' : ''}`}
            onMouseEnter={() => setHoveredInput('n1')}
            onMouseLeave={() => setHoveredInput(null)}
          >
            <label>
              <span className="label-icon">💨</span>
              Input Rotational Speed 
              <span className="variable">(N₁)</span>
            </label>
            <div className="input-wrapper">
              <input 
                type="number" 
                value={n1} 
                onChange={(e) => setN1(Number(e.target.value))}
                min="0"
                max="10000"
              />
              <motion.div 
                className="input-glow"
                initial={{ opacity: 0 }}
                animate={{ opacity: hoveredInput === 'n1' ? 1 : 0 }}
              />
            </div>
            <div className="input-slider">
              <input 
                type="range" 
                min="0" 
                max="10000" 
                step="100"
                value={n1}
                onChange={(e) => setN1(Number(e.target.value))}
              />
            </div>
          </motion.div>

          {/* Status indicator */}
          <motion.div 
            className="calculation-status"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
          >
            <div className={`status-indicator ${isCalculating ? 'calculating' : 'ready'}`}>
              <span className="status-pulse" />
              {isCalculating ? 'COMPUTING...' : 'SYSTEM READY'}
            </div>
          </motion.div>

          {/* --- NEW DOWNLOAD BUTTON --- */}
          <button 
            onClick={generateReport}
            style={{ 
              marginTop: '20px', 
              width: '100%',
              background: 'rgba(102, 126, 234, 0.1)', 
              border: '1px solid rgba(102, 126, 234, 0.5)', 
              color: '#a78bfa', 
              padding: '12px', 
              borderRadius: '8px', 
              cursor: 'pointer',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: '0.8rem',
              textTransform: 'uppercase',
              letterSpacing: '1px',
              transition: 'all 0.3s ease'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = 'rgba(102, 126, 234, 0.2)';
              e.currentTarget.style.color = '#fff';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'rgba(102, 126, 234, 0.1)';
              e.currentTarget.style.color = '#a78bfa';
            }}
          >
            [ ↓ DOWNLOAD DATA LOG ]
          </button>
        </motion.div>

        {/* RIGHT PANEL - Visualization */}
        <motion.div 
          className="gear-card visualization-card"
          whileHover={{ y: -5 }}
          transition={{ duration: 0.3 }}
        >
          {/* Corner accents */}
          <div className="corner-accent top-left" />
          <div className="corner-accent top-right" />
          <div className="corner-accent bottom-left" />
          <div className="corner-accent bottom-right" />

          <div className="visualization-header">
            <h2>
              <span className="header-icon">🎯</span>
              Live Digital Twin
            </h2>
            <div className="header-stats">
              <div className="stat-badge">
                <span className="stat-label">RATIO</span>
                <span className="stat-value">{results.gr}:1</span>
              </div>
            </div>
          </div>

          <div className="gears-wrapper">
            {/* Mechanical Connection Indicators */}
            <motion.div 
              style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                width: '60%',
                height: '2px',
                background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.2) 50%, transparent)',
                zIndex: 0
              }}
              animate={{
                opacity: [0.3, 0.6, 0.3]
              }}
              transition={{
                duration: 2,
                repeat: Infinity,
                ease: "easeInOut"
              }}
            />

            {/* Gear Mesh Zone Indicator */}
            <motion.div
              style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                width: '100px',
                height: '100px',
                border: '2px dashed rgba(102, 252, 241, 0.3)',
                borderRadius: '50%',
                zIndex: 0
              }}
              animate={{
                rotate: 360,
                scale: [1, 1.1, 1]
              }}
              transition={{
                rotate: { duration: 20, repeat: Infinity, ease: "linear" },
                scale: { duration: 3, repeat: Infinity, ease: "easeInOut" }
              }}
            />

            {/* Energy flow line - optimized */}
            <motion.div 
              className="energy-flow"
              animate={{
                opacity: [0.3, 0.7, 0.3]
              }}
              transition={{
                duration: 3,
                repeat: Infinity,
                ease: "easeInOut"
              }}
            />

            {/* Driver Gear - STUNNING 3D SVG */}
            <motion.div 
              className="gear driver"
              whileHover={{ scale: 1.05 }}
              transition={{ type: "spring", stiffness: 200, damping: 18 }}
            >
              <motion.svg
                width={150 + t1 * 1.2}
                height={150 + t1 * 1.2}
                viewBox="-100 -100 200 200"
                style={{ rotate: driverSpring }}
              >
                {/* Metallic gradient definitions */}
                <defs>
                  <radialGradient id="driverGearGradient">
                    <stop offset="0%" stopColor="#667eea" />
                    <stop offset="50%" stopColor="#764ba2" />
                    <stop offset="100%" stopColor="#4c3f91" />
                  </radialGradient>
                  <radialGradient id="driverInnerGlow">
                    <stop offset="0%" stopColor="#a78bfa" stopOpacity="0.8" />
                    <stop offset="70%" stopColor="#667eea" stopOpacity="0.3" />
                    <stop offset="100%" stopColor="#764ba2" stopOpacity="0" />
                  </radialGradient>
                  <filter id="driver3d">
                    <feGaussianBlur in="SourceAlpha" stdDeviation="3" />
                    <feOffset dx="0" dy="3" result="offsetblur" />
                    <feComponentTransfer>
                      <feFuncA type="linear" slope="0.4" />
                    </feComponentTransfer>
                    <feMerge>
                      <feMergeNode />
                      <feMergeNode in="SourceGraphic" />
                    </feMerge>
                  </filter>
                </defs>

                {/* Outer glow ring */}
                <circle cx="0" cy="0" r="75" fill="none" stroke="url(#driverInnerGlow)" strokeWidth="20" opacity="0.4" />

                {/* Generate precise gear teeth */}
                <g filter="url(#driver3d)">
                  {[...Array(t1)].map((_, i) => {
                    const angle = (360 / t1) * i;
                    const toothHeight = 12;
                    const toothWidth = (2 * Math.PI * 60) / t1 * 0.7;
                    return (
                      <g key={i} transform={`rotate(${angle})`}>
                        {/* Tooth body */}
                        <rect
                          x={-toothWidth / 2}
                          y={-60 - toothHeight}
                          width={toothWidth}
                          height={toothHeight}
                          fill="url(#driverGearGradient)"
                          stroke="#4c3f91"
                          strokeWidth="0.5"
                        />
                        {/* Tooth highlight */}
                        <rect
                          x={-toothWidth / 2}
                          y={-60 - toothHeight}
                          width={toothWidth / 3}
                          height={toothHeight}
                          fill="rgba(167, 139, 250, 0.3)"
                        />
                      </g>
                    );
                  })}
                </g>

                {/* Main gear body with metallic effect */}
                <circle cx="0" cy="0" r="60" fill="url(#driverGearGradient)" stroke="#4c3f91" strokeWidth="2" filter="url(#driver3d)" />
                
                {/* Inner circle details */}
                <circle cx="0" cy="0" r="50" fill="none" stroke="rgba(167, 139, 250, 0.3)" strokeWidth="1" />
                <circle cx="0" cy="0" r="40" fill="none" stroke="rgba(167, 139, 250, 0.5)" strokeWidth="2" strokeDasharray="5,3" />
                
                {/* Center hole with depth */}
                <circle cx="0" cy="0" r="20" fill="#1a0b2e" stroke="#667eea" strokeWidth="2" />
                <circle cx="0" cy="0" r="15" fill="#0a0118" />

                {/* Mechanical rivets */}
                {[0, 90, 180, 270].map(angle => (
                  <g key={angle} transform={`rotate(${angle})`}>
                    <circle cx="0" cy="-45" r="3" fill="#a78bfa" stroke="#667eea" strokeWidth="1" />
                  </g>
                ))}

                {/* Speed indicator arrow */}
                <g opacity="0.7">
                  <motion.path 
                    d="M 30 0 Q 35 -3, 40 0 L 36 0 L 36 8 L 34 8 L 34 0 Z" 
                    fill="#66FCF1"
                    initial={{ opacity: 0.5 }}
                    animate={{ opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1.5, repeat: Infinity }}
                  />
                </g>
              </motion.svg>
              
              {/* Power indicator ring - optimized */}
              <motion.div
                style={{
                  position: 'absolute',
                  top: '50%',
                  left: '50%',
                  transform: 'translate(-50%, -50%)',
                  width: `${(150 + t1 * 1.2) + 20}px`,
                  height: `${(150 + t1 * 1.2) + 20}px`,
                  border: '2px solid rgba(102, 252, 241, 0.3)',
                  borderRadius: '50%',
                  borderStyle: 'dashed',
                  pointerEvents: 'none',
                  willChange: 'transform'
                }}
                animate={{
                  rotate: -360
                }}
                transition={{
                  rotate: { duration: 10, repeat: Infinity, ease: "linear" } // Slowed down from 8s
                }}
              />
              
              {/* Label overlay */}
              <div className="gear-label" style={{ position: 'absolute', bottom: '-40px', left: '50%', transform: 'translateX(-50%)' }}>
                <span className="label-title" style={{ color: '#667eea', fontWeight: 700, fontSize: '14px' }}>DRIVER</span>
                <span className="label-rpm" style={{ color: '#a78bfa', fontSize: '12px' }}>{t1}T • {n1} RPM</span>
              </div>
            </motion.div>

            {/* Driven Gear - STUNNING 3D SVG */}
            <motion.div 
              className="gear driven"
              whileHover={{ scale: 1.05 }}
              transition={{ type: "spring", stiffness: 200, damping: 18 }}
            >
              <motion.svg
                width={150 + t2 * 1.2}
                height={150 + t2 * 1.2}
                viewBox="-100 -100 200 200"
                style={{ rotate: drivenSpring }}
              >
                {/* Metallic gradient definitions for driven gear */}
                <defs>
                  <radialGradient id="drivenGearGradient">
                    <stop offset="0%" stopColor="#ff6b35" />
                    <stop offset="50%" stopColor="#f7931e" />
                    <stop offset="100%" stopColor="#c45a26" />
                  </radialGradient>
                  <radialGradient id="drivenInnerGlow">
                    <stop offset="0%" stopColor="#ffb88c" stopOpacity="0.8" />
                    <stop offset="70%" stopColor="#ff6b35" stopOpacity="0.3" />
                    <stop offset="100%" stopColor="#f7931e" stopOpacity="0" />
                  </radialGradient>
                  <filter id="driven3d">
                    <feGaussianBlur in="SourceAlpha" stdDeviation="3" />
                    <feOffset dx="0" dy="3" result="offsetblur" />
                    <feComponentTransfer>
                      <feFuncA type="linear" slope="0.4" />
                    </feComponentTransfer>
                    <feMerge>
                      <feMergeNode />
                      <feMergeNode in="SourceGraphic" />
                    </feMerge>
                  </filter>
                </defs>

                {/* Outer glow ring */}
                <circle cx="0" cy="0" r="75" fill="none" stroke="url(#drivenInnerGlow)" strokeWidth="20" opacity="0.4" />

                {/* Generate precise gear teeth */}
                <g filter="url(#driven3d)">
                  {[...Array(t2)].map((_, i) => {
                    const angle = (360 / t2) * i;
                    const toothHeight = 12;
                    const toothWidth = (2 * Math.PI * 60) / t2 * 0.7;
                    return (
                      <g key={i} transform={`rotate(${angle})`}>
                        {/* Tooth body */}
                        <rect
                          x={-toothWidth / 2}
                          y={-60 - toothHeight}
                          width={toothWidth}
                          height={toothHeight}
                          fill="url(#drivenGearGradient)"
                          stroke="#c45a26"
                          strokeWidth="0.5"
                        />
                        {/* Tooth highlight */}
                        <rect
                          x={-toothWidth / 2}
                          y={-60 - toothHeight}
                          width={toothWidth / 3}
                          height={toothHeight}
                          fill="rgba(255, 184, 140, 0.3)"
                        />
                      </g>
                    );
                  })}
                </g>

                {/* Main gear body with metallic effect */}
                <circle cx="0" cy="0" r="60" fill="url(#drivenGearGradient)" stroke="#c45a26" strokeWidth="2" filter="url(#driven3d)" />
                
                {/* Inner circle details */}
                <circle cx="0" cy="0" r="50" fill="none" stroke="rgba(255, 184, 140, 0.3)" strokeWidth="1" />
                <circle cx="0" cy="0" r="40" fill="none" stroke="rgba(255, 184, 140, 0.5)" strokeWidth="2" strokeDasharray="5,3" />
                
                {/* Center hole with depth */}
                <circle cx="0" cy="0" r="20" fill="#1a0b2e" stroke="#ff6b35" strokeWidth="2" />
                <circle cx="0" cy="0" r="15" fill="#0a0118" />

                {/* Mechanical rivets */}
                {[0, 90, 180, 270].map(angle => (
                  <g key={angle} transform={`rotate(${angle})`}>
                    <circle cx="0" cy="-45" r="3" fill="#ffb88c" stroke="#ff6b35" strokeWidth="1" />
                  </g>
                ))}

                {/* Rotation direction indicator */}
                <g opacity="0.6">
                  <motion.path 
                    d="M 30 0 Q 35 3, 40 0 L 36 0 L 36 -8 L 34 -8 L 34 0 Z" 
                    fill="#ff6b35"
                    initial={{ opacity: 0.5 }}
                    animate={{ opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1.5, repeat: Infinity, delay: 0.5 }}
                  />
                </g>
              </motion.svg>
              
              {/* Power output indicator ring */}
              <motion.div
                style={{
                  position: 'absolute',
                  top: '50%',
                  left: '50%',
                  transform: 'translate(-50%, -50%)',
                  width: `${(150 + t2 * 1.2) + 20}px`,
                  height: `${(150 + t2 * 1.2) + 20}px`,
                  border: '2px solid rgba(255, 107, 53, 0.3)',
                  borderRadius: '50%',
                  borderStyle: 'dashed',
                  pointerEvents: 'none'
                }}
                animate={{
                  rotate: 360,
                  scale: [1, 1.05, 1]
                }}
                transition={{
                  rotate: { duration: 10, repeat: Infinity, ease: "linear" },
                  scale: { duration: 2.5, repeat: Infinity, ease: "easeInOut" }
                }}
              />
              
              {/* Label overlay */}
              <div className="gear-label" style={{ position: 'absolute', bottom: '-40px', left: '50%', transform: 'translateX(-50%)' }}>
                <span className="label-title" style={{ color: '#ff6b35', fontWeight: 700, fontSize: '14px' }}>DRIVEN</span>
                <span className="label-rpm" style={{ color: '#ffb88c', fontSize: '12px' }}>{t2}T • {results.n2} RPM</span>
              </div>
            </motion.div>
          </div>

          {/* Results Panel */}
          <AnimatePresence mode="wait">
            {showResults && (
              <motion.div 
                className="results-panel"
                initial={{ opacity: 0, y: 20, scale: 0.95 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, y: -20, scale: 0.95 }}
                transition={{ duration: 0.4 }}
              >
                <motion.div 
                  className="result-item"
                  whileHover={{ scale: 1.02, borderColor: 'rgba(102, 126, 234, 0.5)' }}
                >
                  <div className="result-icon">⚙️</div>
                  <div className="result-content">
                    <div className="result-label">Gear Ratio</div>
                    <motion.div 
                      className="result-value"
                      key={results.gr}
                      initial={{ scale: 1.2, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      transition={{ type: "spring", stiffness: 300, damping: 20 }}
                    >
                      {results.gr}
                      <span className="result-unit">:1</span>
                    </motion.div>
                    <div className="formula">
                      <code>GR = {t2} ÷ {t1}</code>
                    </div>
                  </div>
                </motion.div>

                <motion.div 
                  className="result-item"
                  whileHover={{ scale: 1.02, borderColor: 'rgba(118, 75, 162, 0.5)' }}
                >
                  <div className="result-icon">🚀</div>
                  <div className="result-content">
                    <div className="result-label">Output Speed</div>
                    <motion.div 
                      className="result-value"
                      key={results.n2}
                      initial={{ scale: 1.2, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      transition={{ type: "spring", stiffness: 300, damping: 20 }}
                    >
                      {results.n2}
                      <span className="result-unit">RPM</span>
                    </motion.div>
                    <div className="formula">
                      <code>N₂ = {n1} ÷ {results.gr}</code>
                    </div>
                  </div>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Export Report Button */}
          <motion.button 
            onClick={generateReport}
            className="export-button"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            whileHover={{ 
              scale: 1.03,
              borderColor: '#66FCF1',
              boxShadow: '0 0 20px rgba(102, 252, 241, 0.3)'
            }}
            whileTap={{ scale: 0.98 }}
            style={{ 
              marginTop: '20px', 
              width: '100%',
              background: 'rgba(0, 0, 0, 0.4)', 
              border: '1px solid rgba(102, 252, 241, 0.3)', 
              color: '#66FCF1', 
              padding: '12px 24px', 
              cursor: 'pointer',
              borderRadius: '8px',
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: '0.85rem',
              fontWeight: '600',
              letterSpacing: '1px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '10px',
              transition: 'all 0.3s ease'
            }}
          >
            <span style={{ fontSize: '1.1rem' }}>📥</span>
            [ DOWNLOAD DATA LOG ]
          </motion.button>
        </motion.div>
      </div>
    </motion.div>
  );
});

GearCalculator.displayName = 'GearCalculator';

export default GearCalculator;